WIP Nestjs message dispatcher
fagbokforlaget/nestjs-message-dispatcher pull request #1
Opened 2023-06-01 05:33 UTC by JERILJOSE96

2023-06-06 10:43 UTC, espresse commented on test/message-dispatcher.spec.ts
> +      jest.spyOn(transport, 'log');
@JERILJOSE96  it should be in the `beforeEach` block, also it should be cleared after each test

2023-06-06 10:43 UTC, espresse commented on test/message-dispatcher.spec.ts
> +      const id = '123-test';
@JERILJOSE96 keep it outside of the test case (in the respective `describe` block), we should make our tests cases as lean as possible, focused on the things you're testing - it helps reading them.

2023-06-07 05:45 UTC, JERILJOSE96 commented on test/message-dispatcher.spec.ts
> +      jest.spyOn(transport, 'log');
done

2023-06-07 05:45 UTC, JERILJOSE96 commented on test/message-dispatcher.spec.ts
> +      const id = '123-test';
moved

2023-06-09 07:43 UTC, espresse requested changes
@JERILJOSE96  it looks very good by now. I think the only piece missing is some examples how to use it in case somebody else would like to use this library. Could you add some examples to README? See our other repos in github for inspiration.

2023-06-13 13:03 UTC, espresse approved these changes
@JERILJOSE96 LGTM :+1:

2023-06-14 12:16 UTC, merged